#!/bin/bash

FILE=./.rundir_rc     
COMMAND_NUM=1
MODE="LIST";
COMMAND_TEXT="";


Help()
{
   # Display Help
   echo "Add description of the script functions here."
   echo
   echo "Syntax: rundir -[aidelh] [<number] [-c <command> "
   echo "options:"
   echo "-a -c <command>           - add a command to the end of the file."
   echo "-i <number> -c <command>  - insert the command at line number."
   echo "-d <number>               - delete the command at line number." 
   echo "-l                        -list the commands."
   echo "-e <number>               -execute the command at sequence <number>."
   echo "-h                        - Print this Help."
   echo
}


createRCFileIfNotExists() {
#check for ./runrc   
  if [ -f $FILE ]; then
    echo "File $FILE exists."
  else
     echo "File $FILE does not exist."
     touch $FILE 
  fi

}
ListContents() 
{
  createRCFileIfNotExists

  while read -r line
  do
    echo "$line"
  done < $FILE
}

AddCommand() 
{
  createRCFileIfNotExists
  echo $1 >> $FILE
}

InsertCommandAtLineNumber() 
{
  createRCFileIfNotExists
  if [ ! -f $FILE ]; then
     echo "File $FILE does not exist."
     exit	
  fi

}


DeleteCommandAtLineNumber() 
{
  createRCFileIfNotExists
  if [ ! -f $FILE ]; then
     echo "File $FILE does not exist."
     exit	
  fi

}


ExecuteCommandAtLineNumber() 
{
  createRCFileIfNotExists
  echo $1
  if [ ! -f $FILE ]; then
     echo "File $FILE does not exist."
     exit	
  fi
  echo $1

}


while getopts ":hai:d:le:c:" option; do
   case $option in
      h) # display Help
         Help
         exit;;
      a) #add
	 MODE="ADD"
	 ;;
      i) #insert
	 MODE="INSERT"
	 ;;
      d) #delete
	 MODE="DELETE"
	 ;;
      l) #list
	 MODE="LIST"
	 ;;
      e) #execute
         COMMAND_NUM=$OPTARG
	 MODE="EXECUTE"
	 ;;
      c) # enter a command
         COMMAND_TEXT=$OPTARG	
	 ;;
     \?) # Invalid option
         echo "Error: Invalid option"
         exit;;
   esac
done

echo $MODE;
echo $COMMAND_TEXT
echo $COMMAND_NUM

case $MODE in
	"LIST") 
		ListContents
		;;
	"EXECUTE") 
		ExecuteCommandAtLineNumber $COMMAND_NUM
		;;
	"INSERT") 
		InsertCommandAtLineNumber $COMMAND_NUM $COMMAND_TEXT
		;;
	"ADD") 
		AddCommand $COMMAND_TEXT
		;;
	"DELETE") 
		DeleteCommandAtLineNumber $COMMAND_NUM 
		;;
esac



