#!/bin/bash

FILE=./.rundir_rc     
COMMAND_NUM=1
#MODE="LIST";
COMMAND_TEXT="";


Help()
{
   # Display Help
   printf "Add description of the script functions here.\n";
   printf "\n" ;
   printf "Syntax: rundir -[aidelh] [<number] [-c <command>\n";
   printf "options:\n";
   printf " -a -c <command>           - add a command to the end of the file.\n"
   printf " -i <number> -c <command>  - insert the command at line number.\n"
   printf " -d <number>               - delete the command at line number.\n" 
   printf " -l                        -list the commands.\n"
   printf " -e <number>               -execute the command at sequence <number>.\n"
   printf " -h                        - Print this Help.\n"
   printf ""
}

NotImplemented()
{
   printf "Operation Not implemented.\n";
}

createRCFileIfNotExists() {
#check for ./runrc   
  if [ -f $FILE ]; then
     printf "File %s exists.\n" "$FILE"
  else
     printf "File %s does not exist.\n" "$FILE"
     touch $FILE 
  fi

}
ListContents() 
{
  createRCFileIfNotExists

  while read -r line
  do
    echo "$line"
  done < $FILE
}

AddCommand() 
{
  createRCFileIfNotExists
  echo $1 >> $FILE
}

InsertCommandAtLineNumber() 
{
	NotImplemented
	exit
  createRCFileIfNotExists
  if [ ! -f $FILE ]; then
     printf "File %s does not exist.\n" "$FILE"
     exit	
  fi

}


DeleteCommandAtLineNumber() 
{
	NotImplemented
	exit
  createRCFileIfNotExists
  if [ ! -f $FILE ]; then
     printf "File %s does not exist.\n" "$FILE"
     exit	
  fi

}


ExecuteCommandAtLineNumber() 
{
  createRCFileIfNotExists
  if [ ! -f $FILE ]; then
     printf "File %s does not exist.\n" "$FILE"
     exit	
  fi
  #get the command from the given line 
  i=1
  while read -r line
  do
    if [ $i -eq $1 ]; then
       command=$line
    fi
    ((i++))
     #printf "Counter %d\n" "$i"
  done < $FILE
  printf "executing command: %s\n" "$command"
  $command
}


while getopts ":hai:d:le:c:" option; do
   case $option in
      h) # display Help
         Help
         exit;;
      a) #add
	 MODE="ADD"
	 ;;
      i) #insert
	 MODE="INSERT"
	 ;;
      d) #delete
	 MODE="DELETE"
	 ;;
      l) #list
	 MODE="LIST"
	 ;;
      e) #execute
         COMMAND_NUM=$OPTARG
	 MODE="EXECUTE"
	 ;;
      c) # enter a command
         COMMAND_TEXT=$OPTARG	
	 ;;
     \?) # Invalid option
         printf "Error: Invalid option"
         exit;;
   esac
done

#printf "MODE = %s\n" "$MODE"
#printf "COMMAND_TEXT = %s\n" "${COMMAND_TEXT}"
#printf "COMMAND_NUM = %s\n" "${COMMAND_NUM}"

case $MODE in
	"LIST") 
		ListContents
		;;
	"EXECUTE") 
		ExecuteCommandAtLineNumber $COMMAND_NUM
		;;
	"INSERT") 
		InsertCommandAtLineNumber $COMMAND_NUM $COMMAND_TEXT
		;;
	"ADD") 
		AddCommand $COMMAND_TEXT
		;;
	"DELETE") 
		DeleteCommandAtLineNumber $COMMAND_NUM 
		;;
esac



